<a href="https://colab.research.google.com/github/dtype2100/TIL/blob/master/text_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances

import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('')

In [ ]:
df.head(1)

title paper         date  \
0  네이버·카카오로도 기차 예매한다…통합 교통 정보 제공(종합)  조선비즈  2021.01.31.   

                                                 url  \
0  https://news.naver.com/main/read.naver?mode=LS...   

                                             content  
0  네이버와 카카오모빌리티는 오는 1일부터 한국철도공사 기차 예매 서비스를 제공한다고 ...

In [ ]:
title_df = df['title']

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(title_df)

In [ ]:
idf = tfidf_vectorizer.idf_

In [ ]:
id = dict(zip(tfidf_vectorizer.get_feature_names(), idf))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf)))

{'0000에': 6.997695096858618, '100': 6.304547916298673, '1000만명': 6.997695096858618, '1000분의': 6.997695096858618, '100만': 5.899082808190508, '100만원': 6.304547916298673, '100조': 6.997695096858618, '11': 6.997695096858618, '110억': 6.997695096858618, '12': 6.081404364984463, '12시간': 6.304547916298673, '12억뷰': 6.997695096858618, '134개국': 6.997695096858618, '153억': 6.997695096858618, '153억원': 6.997695096858618, '17': 5.899082808190508, '191명': 6.592229988750454, '1개사': 6.997695096858618, '1년': 6.081404364984463, '1대1': 6.997695096858618, '1보': 6.592229988750454, '1분기': 6.592229988750454, '1억': 5.388257184424518, '1억뷰': 5.899082808190508, '1억원': 6.997695096858618, '1억회': 6.997695096858618, '1위': 4.395005411414234, '1위도': 6.997695096858618, '1일it템': 6.997695096858618, '1조': 4.107323338962454, '1조2': 6.997695096858618, '1조2153억': 5.388257184424518, '1조2153억원': 6.304547916298673, '1조2천153억': 5.74493212836325, '1조5126억': 6.997695096858618, '1조5126억원': 6.592229988750454, '1조721억원에': 6.997695096858

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


# 코사인 유사도

In [ ]:
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[0.00414094]])

# 유클리디언 유사도

In [ ]:
euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[1.41128244]])

In [ ]:
def l1_normalize(v):
    norm = np.sum(v)
    return v / norm

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[1.41128244]])

# 맨해튼 유사도

In [ ]:
manhattan_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[5.42907802]])