In [1]:
import numpy as np

In [2]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

In [6]:
matrix_2[0][0]

5

In [9]:
%%time
sum_matrix = []

for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append( matrix_1[i][j] + matrix_2[i][j])
        
    sum_matrix.append(temp)

print(sum_matrix)

[[6, 8], [10, 12]]
Wall time: 0 ns


In [13]:
np_sum_matrix = np.array(matrix_1) + np.array(matrix_2)
print(np_sum_matrix)
np_sum_matrix

[[ 6  8]
 [10 12]]


array([[ 6,  8],
       [10, 12]])

In [10]:
%%time
add_one_matrix = []

for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append( matrix_1[i][j] + 1)
        
    add_one_matrix.append(temp)

print(add_one_matrix)

[[2, 3], [4, 5]]
Wall time: 0 ns


In [14]:
np_add_one_matrix = np.array(matrix_1) + 1
print(np_add_one_matrix)
np_add_one_matrix

[[2 3]
 [4 5]]


array([[2, 3],
       [4, 5]])

In [15]:
import time
time.time()

1639964021.491711

In [16]:
import time

size = 10000000

#list
x = list(range(size))
y = list(range(size))

start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린시간", time.time()-start_time)

#adlist
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("넘파이 걸린시간", time.time()-start_time)


리스트 걸린시간 1.1611998081207275
넘파이 걸린시간 0.10970687866210938


In [22]:
a = np.array(list(range(10)))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.dtype

dtype('int32')

In [21]:
a = np.array(list(range(10)), dtype=np.float32)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [23]:
type(a)

numpy.ndarray

In [24]:
b = np.array(a)

In [25]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x = np.uint(32)


In [28]:
x.dtype

dtype('uint32')

In [29]:
x = np.array([1, 2, 3, 4])
print(x.dtype)

int32


In [30]:
x = np.float32([1, 2, 3, 4])
x.dtype

dtype('float32')

In [31]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x.dtype)

float32


In [32]:
x = np.int32(x)
print(x.dtype)

int32


In [35]:
np.issubdtype(x.dtype, np.int64)

False

In [40]:
x = np.array(1)
print(x)
print(x.shape)
print(x.ndim)
print(x.size)

1
()
0
1


In [41]:
x = np.array([1, 2, 3])

print(x)
print(x.shape)
print(x.ndim)
print(x.size)


[1 2 3]
(3,)
1
3


In [42]:
x = np.array([[1], [2], [3]])

print(x)
print(x.shape)
print(x.ndim)
print(x.size)


[[1]
 [2]
 [3]]
(3, 1)
2
3


In [43]:
x = np.array([[1, 2, 3]])

print(x)
print(x.shape)
print(x.ndim)
print(x.size)


[[1 2 3]]
(1, 3)
2
3


In [44]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print(x)
print(x.shape)
print(x.ndim)
print(x.size)


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [45]:
x = np.array([[[1, 2, 3], [4, 5, 6]]])

print(x)
print(x.shape)
print(x.ndim)
print(x.size)


[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
3
6


In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x = np.arange(10.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
x = np.arange(1, 10, 2)
x

array([1, 3, 5, 7, 9])

In [51]:
x = np.arange(1, 10, 0.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [52]:
x = np.arange(10, 1, -0.5)
print(x)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [54]:
x = np.linspace(1, 20, 5)
x

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [55]:
x = np.linspace(1, 20)
x

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [56]:
np.linspace?

In [58]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
x.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
x = np.arange(24).reshape(2, 3, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
x = np.arange(12).reshape(2, 1, 2, 3)
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5]]],


       [[[ 6,  7,  8],
         [ 9, 10, 11]]]])

In [63]:
x = np.array([[1, 2], [3, 4], [5, 6]])


In [68]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
print(x[1:3])

[1 2]


In [70]:
x = np.arange(20).reshape(4, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
print(x[1:3])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [72]:
print(x[1:3, 1:3])

[[ 6  7]
 [11 12]]


In [73]:
x = np.arange(30).reshape(2, 5, -1)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [74]:
print(x[:, 3:5, 1])

[[10 13]
 [25 28]]


In [75]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
a[1][1]

6

In [77]:
a[1, 1]

6

In [78]:
a[[1, 1], [1, 2]]

array([6, 7])

In [79]:
a > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [80]:
a[a > 3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [82]:
a [ a == 1]

array([1])

In [83]:
a[~(a == 1)]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [84]:
a[a != 1]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [85]:
a[(a > 3) & ( a < 8)]

array([4, 5, 6, 7])

In [86]:
np.random.rand(5, 5)

array([[0.11300129, 0.85571154, 0.71411026, 0.28784786, 0.32073261],
       [0.2790515 , 0.03471428, 0.12622533, 0.31855559, 0.19596521],
       [0.33802076, 0.67520359, 0.1811923 , 0.07381021, 0.15351455],
       [0.4209883 , 0.18056122, 0.28247192, 0.29498811, 0.87973823],
       [0.36964937, 0.69933605, 0.36029305, 0.92659766, 0.22035474]])

In [87]:
np.random.rand?

In [173]:
np.random.randint(1, 10)

6

In [91]:
np.random.randint(1, 10, size=(5,))

array([9, 8, 4, 1, 7])

In [179]:
np.random.randint(1, 10, size=(5,2))

array([[7, 1],
       [6, 7],
       [8, 8],
       [8, 8],
       [8, 1]])

In [177]:
np.random.choice(100, size=(3, 4))

array([[95, 65, 23, 46],
       [29, 12, 25, 83],
       [47, 59, 15, 94]])

In [96]:
x = np.array([3, 6, 9, 12])
np.random.choice(x, size=(2, 2))

array([[ 9, 12],
       [ 3,  9]])

In [97]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [99]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
c = np.random.choice(100, size=(3, 4))
c

array([[83, 68, 39, 16],
       [73, 95, 34, 38],
       [42, 12, 67, 94]])

In [104]:
c.ravel()

array([83, 68, 39, 16, 73, 95, 34, 38, 42, 12, 67, 94])

In [108]:
np.ravel(c)

array([83, 68, 39, 16, 73, 95, 34, 38, 42, 12, 67, 94])

In [110]:
np.ravel(c, 'F')

array([83, 73, 42, 68, 95, 12, 39, 34, 67, 16, 38, 94])

In [111]:
c

array([[83, 68, 39, 16],
       [73, 95, 34, 38],
       [42, 12, 67, 94]])

In [114]:
c.flatten()

array([83, 68, 39, 16, 73, 95, 34, 38, 42, 12, 67, 94])

In [113]:
c

array([[83, 68, 39, 16],
       [73, 95, 34, 38],
       [42, 12, 67, 94]])

In [115]:
c.ravel()

array([83, 68, 39, 16, 73, 95, 34, 38, 42, 12, 67, 94])

In [116]:
c

array([[83, 68, 39, 16],
       [73, 95, 34, 38],
       [42, 12, 67, 94]])

In [119]:
x=np.arange(12).reshape(2,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [121]:
print(x.ravel(order='C'))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [120]:
print(x.ravel(order='F'))

[ 0  6  3  9  1  7  4 10  2  8  5 11]


In [125]:
np.ravel?

In [123]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)
print(x)
print(y)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [142]:
x = np.arange(1, 4)
y = np.arange(4, 7)
z = np.arange(8, 11)
print(x)
print(y)
print(z)

[1 2 3]
[4 5 6]
[ 8  9 10]


In [143]:
x.shape

(3,)

In [127]:
np.concatenate?

In [138]:
np.concatenate([x, y],  axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [132]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [133]:
np.concatenate([x, y, z], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [145]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)


In [146]:
print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [147]:
print(x.shape)
print(y.shape)

(2, 5)
(2, 5)


In [150]:
z = np.concatenate([x, y])
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [151]:
z.shape

(4, 5)

In [152]:
z = np.concatenate([x, y], axis=1)
print(z.shape)
z

(2, 10)


array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [153]:
x = np.arange(6).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
print(x)
print(y)
print('----')


[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
----


In [154]:
print(np.concatenate([x,y]))


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [155]:
print(np.concatenate([x,y], axis=1))

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [156]:
np.split?


In [157]:
x= np.arange(12)

In [158]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [159]:
np.split(x4, )

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [160]:
np.split(x, 5)

ValueError: array split does not result in an equal division

In [161]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
np.split(x, 2)

ValueError: array split does not result in an equal division

In [163]:
np.split(x, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [164]:
x = np.arange(12).reshape(4, -1)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [165]:
np.split(x, 2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]