In [ ]:
import numpy as np

In [ ]:
x = np.arange(6).reshape(3, 2)
y = np.arange(6).reshape(2, 3)
print(x)
print("------------")
print(y)

[[0 1]
 [2 3]
 [4 5]]
------------
[[0 1 2]
 [3 4 5]]


In [ ]:
z = x.dot(y)
z

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [ ]:
np.transpose(x)

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.linalg.inv(z) 

array([[ 1.12589991e+15, -2.25179981e+15,  1.12589991e+15],
       [-2.25179981e+15,  4.50359963e+15, -2.25179981e+15],
       [ 1.12589991e+15, -2.25179981e+15,  1.12589991e+15]])

In [ ]:
np.linalg.det(z)

5.329070518200744e-15

In [ ]:
np.mean(x)

2.5

In [ ]:
np.median(x)

2.5

In [ ]:
np.median(z)

14.0

In [ ]:
np.mean(z)

14.0

In [ ]:
np.std(x)

1.707825127659933

In [ ]:
np.std(z)

9.510228411791404

In [ ]:
np.var(x)

2.9166666666666665

In [ ]:
np.var(z)

90.44444444444444

In [ ]:
np.sum(x)

15

```
[[0 1]
 [2 3]
 [4 5]]
```

In [ ]:
np.sum(x, axis=0)

array([6, 9])

In [ ]:
np.sum(x, axis=1)

array([1, 5, 9])

In [ ]:
np.sum?

Signature:
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used w

In [ ]:
x = np.array([1, 2, 3])
x + 1

array([2, 3, 4])

In [ ]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = np.arange(1, 4)
y

array([1, 2, 3])

In [ ]:
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
y = np.arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [ ]:
x + y

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [ ]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
print(x)
print(y)

[[10]
 [20]
 [30]]
[1 2 3]


In [ ]:
x + y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9] 
y = [10, 20, 30, 40, 50, 60, 70, 80, 90]
x = np.array(x).reshape(3, 3)
y = np.array(y).reshape(3, 3)
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
x + y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [ ]:
Z = np.linspace(1, 20, 30) + 10
Z

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [ ]:
Z = np.random.randint(1, 101, size=(2, 10, 10))
Z = np.where(Z >= 50, 1, 2)
Z

array([[[1, 1, 2, 1, 1, 1, 2, 2, 1, 1],
        [2, 2, 1, 2, 2, 1, 2, 2, 2, 1],
        [2, 2, 1, 1, 1, 2, 1, 1, 2, 1],
        [1, 2, 2, 2, 1, 2, 1, 1, 2, 2],
        [1, 1, 1, 1, 2, 2, 2, 1, 1, 1],
        [2, 2, 2, 1, 1, 2, 2, 2, 1, 2],
        [1, 2, 1, 2, 1, 1, 1, 2, 2, 1],
        [1, 2, 2, 2, 2, 2, 1, 2, 2, 1],
        [2, 2, 2, 1, 1, 2, 2, 2, 2, 2],
        [2, 1, 1, 2, 2, 1, 1, 1, 2, 1]],

       [[2, 2, 1, 2, 2, 1, 2, 2, 2, 1],
        [2, 1, 2, 1, 2, 2, 2, 1, 2, 1],
        [1, 1, 1, 2, 1, 2, 1, 2, 2, 1],
        [1, 2, 1, 1, 2, 2, 2, 1, 1, 1],
        [1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
        [2, 2, 2, 2, 1, 1, 1, 2, 2, 2],
        [2, 1, 2, 2, 2, 1, 2, 2, 2, 2],
        [1, 1, 2, 2, 2, 1, 1, 2, 2, 1],
        [1, 1, 1, 1, 1, 1, 2, 1, 2, 1],
        [1, 2, 1, 2, 2, 1, 1, 2, 1, 1]]])

In [ ]:
Z[1, 5:, 5:]

array([[1, 1, 2, 2, 2],
       [1, 2, 2, 2, 2],
       [1, 1, 2, 2, 1],
       [1, 2, 1, 2, 1],
       [1, 1, 2, 1, 1]])

In [ ]:
import pandas as pd

In [ ]:
X = [1, 2, "Three", 4, 5]
X = pd.Series(X)
X

0        1
1        2
2    Three
3        4
4        5
dtype: object

In [ ]:
X[0]

1

In [ ]:
type(X[1:3])

pandas.core.series.Series

In [ ]:
X = X[::-1]
X

0        1
1        2
2    Three
3        4
4        5
dtype: object

In [ ]:
x = [1, 2, 3, 4, 5]
x = pd.Series(x)
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
x[x > 3]

3    4
4    5
dtype: int64

In [ ]:
x + 1

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [ ]:
x * 10

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
x + x

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
x = [1, 2, 3, 4, 5]
x = pd.Series(x)
x = x[::-1]

In [ ]:
x

4    5
3    4
2    3
1    2
0    1
dtype: int64

In [ ]:
x

4    5
3    4
2    3
1    2
0    1
dtype: int64

In [ ]:
x.index

RangeIndex(start=4, stop=-1, step=-1)

In [ ]:
x.values

array([5, 4, 3, 2, 1], dtype=int64)

In [ ]:
x = [1, 2, 3, 4, 5]
x = pd.Series(x, index=['a', 'b', 'c', 'd', 'e'])
x

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
x['a']


1

In [ ]:
x[0]

1

In [ ]:
sub = x[[0, 1]]
print(sub)
print(type(sub))

a    1
b    2
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
x[['c', 'e']]

c    3
e    5
dtype: int64

In [ ]:
x.a

1

In [ ]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [ ]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [ ]:
x.수학

90

In [ ]:
x['수학']

90

In [ ]:
x[0]

90

In [ ]:
x['영어':]

영어    80
과학    95
미술    80
dtype: int64

In [ ]:
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [ ]:
x['영어':'미술']

영어    80
과학    95
미술    80
dtype: int64

In [ ]:
x[1:3]

영어    80
과학    95
dtype: int64

In [ ]:
x['미술']

80

In [ ]:
x[3]

80

In [ ]:
type(x)

pandas.core.series.Series

In [ ]:
x = pd.Series(x, index=['수학', '영어'])
x

수학    90
영어    80
dtype: int64

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a[[1, 4]]

array([1, 4])

In [ ]:
student_1 = {"수학":90, "영어":80, "과학":95, "미술":80}
student_2 = {"수학":70, "영어":90, "과학":100, "미술":70}

In [ ]:
index_1 = ["홍길동" for i in range(len(student_1))] + ["이몽룡" for i in range(len(student_2))] 

In [ ]:
index_2 = [i for i in student_1] + [i for i in student_2]

In [ ]:
value_all = list(student_1.values()) + list(student_2.values())

In [ ]:
index_1

['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']

In [ ]:
index_2

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [ ]:
value_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [ ]:
index_3 = ['A반' for i in range(len(value_all))]
index_3

['A반', 'A반', 'A반', 'A반', 'A반', 'A반', 'A반', 'A반']

In [ ]:
students = pd.Series(value_all, index=[index_3, index_1, index_2])
students

A반  홍길동  수학     90
         영어     80
         과학     95
         미술     80
    이몽룡  수학     70
         영어     90
         과학    100
         미술     70
dtype: int64

In [ ]:
students.index

MultiIndex([('홍길동', '수학'),
            ('홍길동', '영어'),
            ('홍길동', '과학'),
            ('홍길동', '미술'),
            ('이몽룡', '수학'),
            ('이몽룡', '영어'),
            ('이몽룡', '과학'),
            ('이몽룡', '미술')],
           )

In [ ]:
x = [1, None, 2, None, 3, 4, None]
x = np.array(x)
x = pd.Series(x)
x

0       1
1    None
2       2
3    None
4       3
5       4
6    None
dtype: object

In [ ]:
x.sum()

10

In [ ]:
x.max()

4

In [ ]:
x.min()

1

In [ ]:
x.isnull().sum()

3

In [ ]:
x.notnull().sum()

4

In [ ]:
x.dropna()

0    1
2    2
4    3
5    4
dtype: object

In [ ]:
x

0       1
1    None
2       2
3    None
4       3
5       4
6    None
dtype: object

In [ ]:
x.dropna(inplace=True)

In [ ]:
x

0    1
2    2
4    3
5    4
dtype: object

KeyError: 1

In [ ]:
x = [1, None, 2, None, 3, 4, None]
x = np.array(x)
x = pd.Series(x)
x

0       1
1    None
2       2
3    None
4       3
5       4
6    None
dtype: object

In [ ]:
x.fillna(0)

0    1
1    0
2    2
3    0
4    3
5    4
6    0
dtype: int64

In [ ]:
x.fillna(0, inplace=True)

In [ ]:
x

0    1
1    0
2    2
3    0
4    3
5    4
6    0
dtype: int64

In [ ]:
x = pd.Series([1, 2, 3])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])
print(x)
print(y)
print(z)


0    1
1    2
2    3
dtype: int64
0    4
1    5
2    6
dtype: int64
0    7
1    8
2    9
dtype: int64


In [ ]:
pd.concat([x, y, z])

0    1
1    2
2    3
0    4
1    5
2    6
0    7
1    8
2    9
dtype: int64

In [ ]:
pd.concat([x, y, z], verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([0, 1, 2], dtype='int64')

In [ ]:
pd.concat([x, y, z], ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [ ]:
df = pd.concat([x, y, z], ignore_index=True, axis=1)
print(df)
print(type(df))

   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9
<class 'pandas.core.frame.DataFrame'>


In [ ]:
x = pd.Series([1, 2, 3, 4])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])

In [ ]:
pd.concat([x, y, z], axis=1)

0    1    2
0  1  4.0  7.0
1  2  5.0  8.0
2  3  6.0  9.0
3  4  NaN  NaN

In [ ]:
pd.concat([x, y, z], axis=1, join='inner')

0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 10])

In [ ]:
x.add(10)

0    11
1    12
2    13
3    14
4    15
dtype: int64

In [ ]:
x.sub(y)

0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64

In [ ]:
x.mod(2)

0    1
1    0
2    1
3    0
4    1
dtype: int64

In [ ]:
x.div(3)

0    0.333333
1    0.666667
2    1.000000
3    1.333333
4    1.666667
dtype: float64

In [ ]:
x.floordiv(3)

0    0
1    0
2    1
3    1
4    1
dtype: int64

In [ ]:
x.count()

5

In [ ]:
x.min()

1

In [ ]:
x.max()

5

In [ ]:
x.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [ ]:
x = pd.Series([ 26, 10, 25, 27, 29, 1, 2])
x.describe()

count     7.000000
mean     17.142857
std      12.375090
min       1.000000
25%       6.000000
50%      25.000000
75%      26.500000
max      29.000000
dtype: float64

In [ ]:
x.head(3)

0    26
1    10
2    25
dtype: int64

In [ ]:
x.tail()

2    25
3    27
4    29
5     1
6     2
dtype: int64

In [ ]:
pd.date_range(start='2022-01-01', end='2022-01-07')

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start='2022-01-01', periods=7)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start='2022/01/01', periods=7, freq='2D')

DatetimeIndex(['2022-01-01', '2022-01-03', '2022-01-05', '2022-01-07',
               '2022-01-09', '2022-01-11', '2022-01-13'],
              dtype='datetime64[ns]', freq='2D')

In [ ]:
pd.date_range(start="01-01-2022", periods=7, freq='W')

DatetimeIndex(['2022-01-02', '2022-01-09', '2022-01-16', '2022-01-23',
               '2022-01-30', '2022-02-06', '2022-02-13'],
              dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
pd.date_range(start='2018-04-24', end='2018-04-27')

DatetimeIndex(['2018-04-24', '2018-04-25', '2018-04-26', '2018-04-27'], dtype='datetime64[ns]', freq='D')

In [ ]:
x = pd.to_datetime(['2020-01-02 03:45', '2021-12-24 23:59'])
x

DatetimeIndex(['2020-01-02 03:45:00', '2021-12-24 23:59:00'], dtype='datetime64[ns]', freq=None)

In [ ]:
x +  pd.DateOffset(1)

DatetimeIndex(['2020-01-03 03:45:00', '2021-12-25 23:59:00'], dtype='datetime64[ns]', freq=None)

In [ ]:
x.year

Int64Index([2020, 2021], dtype='int64')

In [ ]:
x.month

Int64Index([1, 12], dtype='int64')

In [ ]:
x - pd.to_datetime('2020-02-12 15:39')

TimedeltaIndex(['-42 days +12:06:00', '681 days 08:20:00'], dtype='timedelta64[ns]', freq=None)

In [ ]:
x = [None,1,2,3,4,5]
y = pd.Series([x[np.random.randint(0,6)]for i in range(20)])


In [ ]:
x

[None, 1, 2, 3, 4, 5]

In [ ]:
y

0     5.0
1     5.0
2     1.0
3     4.0
4     3.0
5     1.0
6     5.0
7     1.0
8     5.0
9     4.0
10    NaN
11    4.0
12    4.0
13    2.0
14    4.0
15    4.0
16    5.0
17    NaN
18    2.0
19    5.0
dtype: float64

In [ ]:
y.isnull().sum()

2

In [ ]:
y.dropna()

0     5.0
1     5.0
2     1.0
3     4.0
4     3.0
5     1.0
6     5.0
7     1.0
8     5.0
9     4.0
11    4.0
12    4.0
13    2.0
14    4.0
15    4.0
16    5.0
18    2.0
19    5.0
dtype: float64

In [ ]:
y.mean()

3.5555555555555554

In [ ]:
y.fillna(y.mean())

0     5.000000
1     5.000000
2     1.000000
3     4.000000
4     3.000000
5     1.000000
6     5.000000
7     1.000000
8     5.000000
9     4.000000
10    3.555556
11    4.000000
12    4.000000
13    2.000000
14    4.000000
15    4.000000
16    5.000000
17    3.555556
18    2.000000
19    5.000000
dtype: float64