## 문제 1 
numpy 패키지를 임포트 하세요

In [8]:
import numpy as np

## 문제 2

numpy 버전을 출력하세요

In [ ]:
print(np.__version__)

NameError: ignored

## 문제 3

크기가 10인 zero vector Z 를 만드세요


In [ ]:
z= np.zeros(10)
print(z)

NameError: ignored

## 문제 4

위에서 만든 zero vector의 5번째 값을 1로 수정하시오

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 문제 5

10에서 49까지 범위의 값을 갖는 벡터 Z를 만드세요

In [ ]:
Z= np.arange(10,50)
print(z)

NameError: ignored

#문제 6

위에서 만든 벡터 Z를 역순으로 만드세요

In [ ]:
z[::-1]

NameError: ignored

## 문제 7


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1로 바꾸세요

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 문제 8
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1인 새로운 벡터를 만드세요

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## 문제 9

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  벡터를 2x5 행렬로 바꾸세요

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 문제 10
```
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
```
a 와 b를 아래와 같이 행 기준으로 합치세요
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [12]:

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 문제 11
```
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

a와 b를 아래와 같이 열 기준으로 합치세요
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

```



[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 문제 12

0에서 8의 값을 갖는 3x3 행렬을 만드세요


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 문제 13

다음과 같은 행렬 [1,2,0,0,4,0] 에서 0이 아닌 값의 인덱스를 찾으세요 

(array([0, 1, 4]),)


## 문제 14

3x3 크기를 가지는 단위 행렬을 만드세요

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 문제 15

shape가 (3, 3, 3)인 랜덤값을 가지는 3차원 행렬을 만드세요

[[[0.94432862 0.04951614 0.29317509]
  [0.99795163 0.29675516 0.90123103]
  [0.19374989 0.29879454 0.33346999]]

 [[0.42530842 0.66715168 0.76739813]
  [0.17442628 0.06646691 0.88176654]
  [0.7575422  0.25425906 0.69130609]]

 [[0.54035373 0.74183953 0.71902144]
  [0.906154   0.21976156 0.26258863]
  [0.73261948 0.1254483  0.97203616]]]


## 문제 16

Create a 10x10 array with random values and find the minimum and maximum
values

임의의 값으로 채워진 10x10 행렬을 만들고 그 행렬의 최소값과 최대값을 찾으세요.

0.014910326728743373 0.9975822149845712


## 문제 17

Create a random vector of size 30 and find the mean value

크기가 30인 임의의 벡터를 만들고 평균값을 찾으세요.

0.5676736302376008


## 문제 18

Create a 2d array with 1 on the border and 0 inside

테두리가 1이고 내부가 0으로 채워진 2차원 행렬을 만드세요.

## 문제 19

What is the result of the following expression? 

다음 연산의 결과는 유추하세요.

False

## 문제 20

Create a vector of size 10 with values ranging from 0 to 1, both excluded

0에서 1 사이에 균등하게 배분된 값을 반환하는 벡터를 생성합니다(0, 1을 포함)

그 다음 처음과 마지막값을 제외한 배열을 출력하세요(출력하는 배열의 크기는 10입니다.).

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 문제 21

Create a random vector of size 10 and sort it

크기가 10인 임의의 벡터를 만들고 정렬하세요.

[0.14337895 0.16515857 0.23489601 0.26305674 0.28416904 0.38331113
 0.40315992 0.50086449 0.76905631 0.86165008]


## 문제 22

Create random vector of size 10 and replace the maximum value by 0

크기가 10인 임의의 벡터를 만들고 최대값을 0으로 바꾸세요.

[0.483974   0.40540727 0.19330724 0.37986132 0.03874309 0.3459543
 0.52953417 0.5398927  0.         0.56540744]



## 문제 23

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

```

a, b 두 벡터의 같은 위치에 있는 값이 같은 인덱스를 구하세요
```
결과 예)
(array([1, 3, 5, 7]),)
```

(array([1, 3, 5, 7]),)

## 문제 24

```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

a 에서 5이상 10 이하의 값만 가지는 벡터를 만드세요


[ 6  9 10]


array([ 6,  9, 10])