## 문제 1 
numpy 패키지를 임포트 하세요

In [1]:
import numpy as np

## 문제 2

numpy 버전을 출력하세요

In [2]:
np.__version__

'1.20.3'

## 문제 3

크기가 10인 zero vector Z 를 만드세요


In [5]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 문제 4

위에서 만든 zero vector의 5번째 값을 1로 수정하시오

In [6]:
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 문제 5

10에서 49까지 범위의 값을 갖는 벡터 Z를 만드세요

In [7]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 문제 6

위에서 만든 벡터 Z를 역순으로 만드세요

In [8]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 문제 7


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1로 바꾸세요

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr[arr % 2 == 1 ] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 문제 8
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1인 새로운 벡터를 만드세요

In [15]:
arr = np.array([10, 2, 5, 6, -3, 8, 12])
print(np.where(arr % 2 == 1, -1, arr))
print(arr)

[10  2 -1  6 -1  8 12]
[10  2  5  6 -3  8 12]


## 문제 9

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  벡터를 2x5 행렬로 바꾸세요

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr = arr.reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 문제 10
```
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
```
a 와 b를 아래와 같이 행 기준으로 합치세요
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [18]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a, b]))
print(np.vstack([a, b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 문제 11
```
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

a와 b를 아래와 같이 열 기준으로 합치세요
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

```



In [20]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a, b], axis=1))
print(np.hstack([a, b]))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 문제 12

0에서 8의 값을 갖는 3x3 행렬을 만드세요


In [21]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 문제 13

다음과 같은 행렬 [1,2,0,0,4,0] 에서 0이 아닌 값의 인덱스를 찾으세요 

In [22]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

## 문제 14

3x3 크기를 가지는 단위 행렬을 만드세요

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 문제 15

shape가 (3, 3, 3)인 랜덤값을 가지는 3차원 행렬을 만드세요

In [24]:
np.random.random((3, 3, 3))

array([[[0.79013052, 0.60581704, 0.10791204],
        [0.04223534, 0.71464607, 0.0860949 ],
        [0.84669914, 0.34213561, 0.16648012]],

       [[0.9922089 , 0.71124208, 0.03285947],
        [0.33451053, 0.34606351, 0.63920277],
        [0.50285534, 0.07277564, 0.59555375]],

       [[0.4771227 , 0.59429557, 0.27376984],
        [0.25913263, 0.49176866, 0.91603613],
        [0.110817  , 0.25842933, 0.58002504]]])

## 문제 16

Create a 10x10 array with random values and find the minimum and maximum
values

임의의 값으로 채워진 10x10 행렬을 만들고 그 행렬의 최소값과 최대값을 찾으세요.

In [26]:
Z = np.random.random((10, 10))
print(Z)
print(Z.max())
print(Z.min())

[[0.419609   0.62133669 0.69943831 0.87470159 0.55833069 0.10924219
  0.59267158 0.23633664 0.55082053 0.79834994]
 [0.4298697  0.05671469 0.53835221 0.66217003 0.09877896 0.56440631
  0.67540432 0.01642794 0.34537103 0.70929677]
 [0.48066989 0.32735397 0.4231696  0.38445693 0.87562448 0.67495315
  0.80478369 0.5126598  0.84538754 0.50100564]
 [0.44142638 0.88949761 0.1580998  0.19135166 0.94850357 0.69634792
  0.93640273 0.83181474 0.73182495 0.04980357]
 [0.44121227 0.36822892 0.13497895 0.75937693 0.11272066 0.6352037
  0.44227813 0.6624992  0.3075949  0.19623532]
 [0.83252944 0.82309762 0.48166825 0.13676358 0.24718813 0.16739501
  0.03248912 0.05971288 0.46894597 0.86955553]
 [0.3514866  0.20703712 0.58009886 0.6257431  0.17368828 0.03057854
  0.65255851 0.75379386 0.61727    0.39477483]
 [0.29789684 0.10193606 0.27460946 0.79577657 0.93851855 0.75030722
  0.19400811 0.60217197 0.68930687 0.06272318]
 [0.27717291 0.23715127 0.66802761 0.46216215 0.41113692 0.98101598
  0.6411225  

## 문제 17

Create a random vector of size 30 and find the mean value

크기가 30인 임의의 벡터를 만들고 평균값을 찾으세요.

In [29]:
Z = np.random.random(30)
print(Z)

print(np.mean(Z))
print(Z.mean())

[0.35693852 0.55186535 0.83127179 0.44715891 0.55827731 0.53474112
 0.18524535 0.11052225 0.98725795 0.82043259 0.1075538  0.55895553
 0.97322341 0.20153526 0.15098823 0.14279948 0.81928017 0.29233756
 0.03884376 0.83590559 0.2408385  0.31962688 0.67641332 0.82963927
 0.47111791 0.05881161 0.80860119 0.25232001 0.02479535 0.54510458]
0.4577467514076506
0.4577467514076506


## 문제 18

10*10 크기를 가지고 테두리가 1이고 내부가 0으로 채워진 2차원 행렬을 만드세요.

In [35]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 문제 19

What is the result of the following expression? 

다음 연산의 결과는 유추하세요.

In [36]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [37]:
3 * 0.1

0.30000000000000004

## 문제 20

Create a vector of size 10 with values ranging from 0 to 1, both excluded

0에서 1 사이에 균등하게 배분된 값을 반환하는 벡터를 생성합니다(0, 1을 포함)

그 다음 처음과 마지막값을 제외한 배열을 출력하세요(출력하는 배열의 크기는 10입니다.).

In [40]:
Z = np.linspace(0, 1, 12)[1:-1]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 문제 21

Create a random vector of size 10 and sort it

크기가 10인 임의의 벡터를 만들고 정렬하세요.

In [44]:
Z = np.random.random(10)
Z.sort()
print(Z)
print(Z[::-1])

[0.11426483 0.23337664 0.30335532 0.30561397 0.32783978 0.36913315
 0.64295535 0.68289284 0.83941339 0.9999057 ]
[0.9999057  0.83941339 0.68289284 0.64295535 0.36913315 0.32783978
 0.30561397 0.30335532 0.23337664 0.11426483]


## 문제 22

Create random vector of size 10 and replace the maximum value by 0

크기가 10인 임의의 벡터를 만들고 최대값을 0으로 바꾸세요.

In [48]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.94470398 0.42516606 0.25568559 0.9063159  0.01511295 0.75334065
 0.15673407 0.4675114  0.79624942 0.38302608]
[0.         0.42516606 0.25568559 0.9063159  0.01511295 0.75334065
 0.15673407 0.4675114  0.79624942 0.38302608]



## 문제 23

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

```

a, b 두 벡터의 같은 위치에 있는 값이 같은 인덱스를 구하세요
```
결과 예)
(array([1, 3, 5, 7]),)
```

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

## 문제 24

```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

a 에서 5이상 10 이하의 값만 가지는 벡터를 만드세요


In [50]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
ind = np.where((a >= 5) & (a <= 10))
a[ind]

array([ 6,  9, 10])