## 문제 1 
numpy 패키지를 임포트 하세요

In [9]:
import numpy as np

## 문제 2

numpy 버전을 출력하세요

In [8]:
print(np.__version__)

1.20.3


## 문제 3

크기가 10인 zero vector Z 를 만드세요


In [78]:
x = zeros([10])
x

NameError: name 'zeros' is not defined

## 문제 4

위에서 만든 zero vector의 5번째 값을 1로 수정하시오

In [19]:
a = np.zeros([10])
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 문제 5

10에서 49까지 범위의 값을 갖는 벡터 Z를 만드세요

In [80]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#문제 6

위에서 만든 벡터 Z를 역순으로 만드세요

In [81]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 문제 7


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1로 바꾸세요

In [83]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr        

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 문제 8
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1인 새로운 벡터를 만드세요

In [88]:
arr = np.array([10, 2, 5, 6, -3, 8, 12])
print(np.where(arr % 2 == 1, -1, arr))
print(arr)

[10  2 -1  6 -1  8 12]
[10  2  5  6 -3  8 12]


## 문제 9

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  벡터를 2x5 행렬로 바꾸세요

In [89]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 문제 10
```
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
```
a 와 b를 아래와 같이 행 기준으로 합치세요
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [91]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a,b]))
print((np.vstack(a, b))

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_7928/349463834.py, line 4)

## 문제 11
```
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

a와 b를 아래와 같이 열 기준으로 합치세요
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

```



In [4]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a + b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## 문제 12

0에서 8의 값을 갖는 3x3 행렬을 만드세요


TypeError: unsupported operand type(s) for -: 'list' and 'int'

## 문제 13

다음과 같은 행렬 [1,2,0,0,4,0] 에서 0이 아닌 값의 인덱스를 찾으세요 

In [14]:
arr1 =  np.array[1,2,0,0,4,0]
print(arr1[1][4])

TypeError: 'builtin_function_or_method' object is not subscriptable

## 문제 14

3x3 크기를 가지는 단위 행렬을 만드세요

In [16]:
np.random.rand(3, 3)

array([[0.45300948, 0.25259959, 0.0456848 ],
       [0.74438896, 0.04639682, 0.57153887],
       [0.11212253, 0.58825487, 0.83710771]])

## 문제 15

shape가 (3, 3, 3)인 랜덤값을 가지는 3차원 행렬을 만드세요

In [17]:
np.random.rand(3, 3, 3)

array([[[0.31648241, 0.90479311, 0.40223246],
        [0.99882093, 0.22218288, 0.61882396],
        [0.83607246, 0.23952027, 0.81171816]],

       [[0.49458324, 0.56443756, 0.95043448],
        [0.37138861, 0.25746656, 0.73148004],
        [0.8999209 , 0.09213432, 0.70494808]],

       [[0.84079972, 0.46348749, 0.52339249],
        [0.53598952, 0.39569589, 0.9751319 ],
        [0.38653862, 0.72541895, 0.77888555]]])

## 문제 16

Create a 10x10 array with random values and find the minimum and maximum
values

임의의 값으로 채워진 10x10 행렬을 만들고 그 행렬의 최소값과 최대값을 찾으세요.

In [20]:
x = np.random.rand(10, 10)
print(x.max())
print(x. min())

0.992428588403597
0.0005009031618389281


## 문제 17

Create a random vector of size 30 and find the mean value

크기가 30인 임의의 벡터를 만들고 평균값을 찾으세요.

In [26]:
a = np.random.rand(30)
print(a.mean())

0.45661572897408226


## 문제 18

Create a 2d array with 1 on the border and 0 inside

테두리가 1이고 내부가 0으로 채워진 2차원 행렬을 만드세요.

In [99]:
Z = np.zeros((10, 10))
Z[1:-1, 1:-1] = 0
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 문제 19

What is the result of the following expression? 

다음 연산의 결과는 유추하세요.

False

## 문제 20

Create a vector of size 10 with values ranging from 0 to 1, both excluded

0에서 1 사이에 균등하게 배분된 값을 반환하는 벡터를 생성합니다(0, 1을 포함)

그 다음 처음과 마지막값을 제외한 배열을 출력하세요(출력하는 배열의 크기는 10입니다.).

In [102]:
z = np.linspace(0, 1, 12)[1:-1]
z


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 문제 21

Create a random vector of size 10 and sort it

크기가 10인 임의의 벡터를 만들고 정렬하세요.

In [103]:
z = np.random.rand(10)
z.sort()
z

array([0.0437397 , 0.22538391, 0.22804987, 0.28969653, 0.35628283,
       0.49562835, 0.61171735, 0.62393488, 0.73280668, 0.75572421])

## 문제 22

Create random vector of size 10 and replace the maximum value by 0

크기가 10인 임의의 벡터를 만들고 최대값을 0으로 바꾸세요.

In [105]:
x = np.random.randㅐㅡ(10)
print(x)


AttributeError: module 'numpy.random' has no attribute 'randᅢᅳ'


## 문제 23

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

```

a, b 두 벡터의 같은 위치에 있는 값이 같은 인덱스를 구하세요
```
결과 예)
(array([1, 3, 5, 7]),)
```

In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a + b

array([ 8,  4, 13,  4, 10,  8, 12,  8, 14, 14])

## 문제 24

```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

a 에서 5이상 10 이하의 값만 가지는 벡터를 만드세요


In [70]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
if a <= 10: 
    print(a)
elif a >= 5:
    print(a)



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()