## 문제 1


판다스를 import 하고 버전을 출력하세요

In [98]:
import pandas as pd
print(pd.__version__)

1.3.4


## 문제 2

아래 list, numpy array, dictionary를 활용해 pandas series를 출력하세요

```
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [104]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
print(mylist)
print(myarr)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mylist)
print("ser1")
print(ser1)

ser2 = pd.Series(myarr)
print("ser2")
print(ser2)

ser3 = pd.Series(mydict)
print("3")
print(3)

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
ser1
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
ser2
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
3
3


## 문제 3

두 series의 값을 포함하는 dataframe을 출력하세요
```
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
```

In [23]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df = pd.DataFrame([ser1, ser2])
df

0  1  2  3  4  5  6  7  8  9   ...  16  17  18  19  20  21  22  23  24  25
0  a  b  c  e  d  f  g  h  i  j  ...   q   r   s   t   u   v   w   x   y   z
1  0  1  2  3  4  5  6  7  8  9  ...  16  17  18  19  20  21  22  23  24  25

[2 rows x 26 columns]

## 문제 4

ser1 Series에서 ser2 Series에 있는 요소들을 제외한 나머지 요소를 출력하세요

```
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [110]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

## 문제 5

ser의 최소값, 25번째 백분위수(25th percentile), 중앙값(median), 75번째 백분위수(75th percentile) 및 최대값을 계산합니다. 

```

ser = pd.Series(np.random.normal(10, 5, 25))
```

In [117]:
ser = pd.Series(np.random.normal(10, 5, 25))
print(ser.describe())
np.percentile(ser, q=[0, 15, 50, 75, 100])

count    25.000000
mean     10.456601
std       4.687715
min      -0.773500
25%       7.745071
50%       9.592067
75%      14.201607
max      19.852414
dtype: float64


array([-0.77350008,  6.79246864,  9.59206723, 14.20160651, 19.85241433])

In [112]:
ser = pd.Series(np.random.normal(10, 5, 25))
ser.median()

10.704977723230256

## 문제 6

아래 ser Series의 각 고유 값과 빈도 수를 계산합니다.

```
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

```

In [49]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.unique()

array(['b', 'd', 'f', 'g', 'h', 'c', 'e', 'a'], dtype=object)

array(['a', 'h', 'd', 'd', 'e', 'a', 'f', 'h', 'c', 'g', 'c', 'd', 'c',
       'e', 'c', 'a', 'h', 'a', 'f', 'g', 'e', 'd', 'f', 'c', 'a', 'e',
       'f', 'g', 'f', 'f'], dtype='<U1')

## 문제 7

Series ser을 7*5 행렬로 전환하세요
전환시 재배열되는 요소의 순서는 아래 예시를 참고해주세요
[0,1,2,3] 
=>  [ [0, 1]
     ,[2, 3]] 
```
ser = pd.Series(np.random.randint(1, 10, 35))
```

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34


In [58]:
ser = pd.Series(np.random.randint(1, 10, 35))
np.array(ser).reshape(7, 5)


array([[9, 8, 6, 1, 5],
       [9, 1, 7, 2, 2],
       [2, 6, 9, 6, 6],
       [2, 4, 3, 1, 8],
       [8, 9, 9, 6, 2],
       [5, 1, 9, 7, 6],
       [9, 5, 4, 3, 4]])

## 문제 8

ser에서 3의 배수인 숫자의 위치를 찾으세요.
```
ser = pd.Series(np.random.randint(1, 10, 7))
```

0    4
1    7
2    3
3    3
4    8
5    8
6    1
dtype: int64


(array([2, 3]),)

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))
ser() 

## 문제 9

ser1 및 ser2를 수직 및 수평으로 쌓은(stack) 값을 각각 Series 및 dataframe으로 출력하세요.
```
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [69]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
ser = ser1, ser2
pd.DataFrame(ser)


0  1  2  3  4
0  0  1  2  3  4
1  a  b  c  d  e

## 문제 10

일련의 문자열을 datetime으로 변환해 주세요

```
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

In [77]:
ser = pd.to_datetime(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser.year

Int64Index([2010, 2011, 2012, 2013, 2014, 2015], dtype='int64')

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

## 문제 11

각 과일의 무게 평균 계산해 주세요 

```
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
```

In [90]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))


apple     4.000000
banana    7.333333
carrot    5.666667
dtype: float64

## 문제 12

ser에 누락된 날짜와 값이 있습니다. 누락된 날짜를 모두 표시하고 이전 날짜의 값으로 채우십시오.

```
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
#> 2000-01-01     1.0
#> 2000-01-03    10.0
#> 2000-01-06     3.0
#> 2000-01-08     NaN
#> dtype: float64
```

In [96]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser.dropna()

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
dtype: float64

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

## 문제 13

가격이 가장 높은 제조업체, 모델 및 유형은 무엇입니까?

Price 값이 가장 높은 셀의 행과 열 번호는 무엇입니까?

찾아낸 행과 열번호에 대응하는 값을 반환해주세요

https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv


[58]
[4]
61.9


61.9

## 문제 14

Type 열의 이름을 df에서 CarType으로 바꾸고 열 이름의 '.'를 '_'로 바꾸세요

https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## 문제 15

df에 누락된 값이 있는지 확인하세요.

입력: https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv

## 문제 16

Min.Price 및 Max.Price 열의 누락된 값을 각각의 평균으로 교체하세요

입력: df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091
