In [35]:
import requests
from bs4 import BeautifulSoup
from konlpy.tag import Mecab
mecab = Mecab()

def get_news(url):
    headers = {"user-agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"}
    response = requests.get(url, headers = headers)
    html = BeautifulSoup(response.text, 'html.parser')
    article = html.select_one("#articleBodyContents").text

    #[for token in mecab.pos(article) if token [1][0] in ["N", "V"]] #야 인덱스 2번쓰면 스트링에도 인덱스 들어가네 아 씨바 이걸 지금..
    article = " ".join([token[0] for token in mecab.pos(article) if token[1] in ["NNG", "VV", "NNP"]]) #여기에 조인을 걸어서 합쳐

    return article
    

urls = ['https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=105&oid=018&aid=0004430108',
'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=001&aid=0011614790',
'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=014&aid=0004424362',
'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=119&aid=0002402191',
'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=030&aid=0002882728']

docs=[]
for url in urls:
    docs.append(get_news(url))

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

count_vect = CountVectorizer(max_df=0.85, max_features=10000)
word_count_vector = count_vect.fit_transform(docs)

In [45]:
doc_ls = [doc.split() for doc in docs]

In [47]:
print(doc_ls)

[['과기', '정통부', '유영민', '장관', '참석', '기념행사', '투입', '여종', '데이터', '구축', '민간', '클라우드', '외부', '연계', '체계', '개방', '강화', '데일리', '이재운', '기자', '국가', '차원', '빅', '데이터', '활용', '시대', '산업', '창출', '기존', '산업', '변화', '이르', '혁신', '장', '센터', '문', '분야', '데이터', '경제', '발전', '정부', '청사진', '현실', '구현', '계획', '과학', '기술', '정보', '통신부', '서울', '중구', '대한', '상공', '회의소', '데이터', '생태', '조성', '혁신', '성장', '기반', '마련', '빅', '데이터', '플랫', '폼', '센터', '출범식', '행사', '개최', '유영민', '과기', '정통부', '장관', '노웅래', '국회', '과학', '기술', '정보', '방송', '통신', '위원회', '위원장', '참가', '분야', '센터', '간', '투입', '이미지', '픽사', '베이', '빅', '데이터', '데이터', '활용', '혁신', '장', '이루', '문재', '정부', '경제', '성장', '핵심', '요소', '문재인', '대통령', '들', '데이터', '활용', '정보', '보호', '보안', '중요', '강조', '맥락', '속', '빅', '데이터', '센터', '공공', '민간', '협업', '활용', '양질', '데이터', '생산', '구축', '플랫', '폼', '수집', '분석', '유통', '역할', '담당', '과기', '정통부', '분야', '플랫', '폼', '연계', '기관', '센터', '구축', '투입', '계획', '올해', '규모', '사업', '추진', '대상', '분야', '금융', '카드', '환경', '한국', '수자원', '공사', '문화', '한국', '문화', '정보원', '교통', '한국', '교통', 

In [50]:
tokens = []
for i in range(len(doc_ls)):
    nodes = list(set(doc_ls[i]))
    tokens.append(nodes)
print(tokens)

[['가', '추진', '계층', '있', '공사', '베이', '최신', '확보', '수행', '클라우드', '신', '산림', '구성', '모색', '보', '편리', '스냅', '카드', '픽사', '선정', '평가', '맥락', '원하', '제고', '기관', '흥원', '경우', '영상', '외부', '환경', '우리나라', '금지', '달', '홈', '정통부', '정부', '수집', '국립암센터', '적용', '청사진', '폼', '대한', '기존', '강조', '대통령', '활용', '밖', '문화', '공급', '이용', '방송', '알고리즘', '장관', '기술', '네이버', '지원', '연속', '비즈', '시대', '마련', '필요', '노웅래', '협업', '생태계', '이르', '경쟁력', '대출', '우스', '임업', '실제', '과기', '체계', '신용', '검색', '교통', '센터', '참가', '보안', '신규', '등록', '단계', '데이터', '공모', '하', '이용자', '완료', '높이', '출범식', '분석', '차원', '대한민국', '뉴스', '공공', '나아가', '생산', '제작', '오늘', '빅', '연계', '소상', '관람', '세계', '운영', '강화', '민간', '도구', '이미지', '중구', '담당', '기업', '위원장', '주요', '예술', '요소', '연간', '발걸음', '문재인', '관리', '개선', '유영민', '청', '한국', '시장', '소', '해소', '구독', '조성', '문', '향상', '여종', '중요', '간', '품질', '중소기업', '국회', '무단', '맞춤', '초석', '수요', '사례', '기준', '문재', '가능', '개최', '전략', '유통', '집중', '통신부', '전망', '정책', '산업', '핵심', '거버넌스', '종합', '회의소', '논의', '생활', '담', '놓', '헬', '인공지능', '기반', '창출', '융

In [57]:
token = doc_ls[0]

In [58]:
vocab = tokens[0]

In [62]:
token = doc_ls[0]
vocab = tokens[0]

vocab2id = { vocab[i] : i for i in range(len(vocab))}
id2vocab = { i : vocab[i] for i in range(len(vocab))}

print (vocab2id)
print (id2vocab)

{'가': 0, '추진': 1, '계층': 2, '있': 3, '공사': 4, '베이': 5, '최신': 6, '확보': 7, '수행': 8, '클라우드': 9, '신': 10, '산림': 11, '구성': 12, '모색': 13, '보': 14, '편리': 15, '스냅': 16, '카드': 17, '픽사': 18, '선정': 19, '평가': 20, '맥락': 21, '원하': 22, '제고': 23, '기관': 24, '흥원': 25, '경우': 26, '영상': 27, '외부': 28, '환경': 29, '우리나라': 30, '금지': 31, '달': 32, '홈': 33, '정통부': 34, '정부': 35, '수집': 36, '국립암센터': 37, '적용': 38, '청사진': 39, '폼': 40, '대한': 41, '기존': 42, '강조': 43, '대통령': 44, '활용': 45, '밖': 46, '문화': 47, '공급': 48, '이용': 49, '방송': 50, '알고리즘': 51, '장관': 52, '기술': 53, '네이버': 54, '지원': 55, '연속': 56, '비즈': 57, '시대': 58, '마련': 59, '필요': 60, '노웅래': 61, '협업': 62, '생태계': 63, '이르': 64, '경쟁력': 65, '대출': 66, '우스': 67, '임업': 68, '실제': 69, '과기': 70, '체계': 71, '신용': 72, '검색': 73, '교통': 74, '센터': 75, '참가': 76, '보안': 77, '신규': 78, '등록': 79, '단계': 80, '데이터': 81, '공모': 82, '하': 83, '이용자': 84, '완료': 85, '높이': 86, '출범식': 87, '분석': 88, '차원': 89, '대한민국': 90, '뉴스': 91, '공공': 92, '나아가': 93, '생산': 94, '제작': 95, '오늘': 96, '빅': 97, '연계': 98, '소상': 9

In [63]:
import numpy as np

vocab_len = len(vocab)

weight_edge = np.zeros((vocab_len, vocab_len), dtype=np.float32)

scores = np.ones(vocab_len, dtype=np.float32)

window_size = 4

covered_coocurrences = []

for window_start in range(0, len(token)-window_size +1):
    window = token[window_start : window_start + window_size]
    for i in range(window_size -1):
        for j in range(i+1, window_size):
            
            if window[i] in vocab and window[i] in vocab:
                index_of_i = window_start + i
                index_of_j = window_start + j
                
                if (index_of_i, index_of_j) not in covered_coocurrences:
                    weight_edge[vocab2id[window[i]]][vocab2id[window[j]]] =1
                    weight_edge[vocab2id[window[j]]][vocab2id[window[i]]] =1
                    covered_coocurrences.append((index_of_i, index_of_j))

print(weight_edge)

for i in range(vocab_len):
    row_sum = weight_edge[i].sum()
    weight_edge[i] = weight_edge[i] / row_sum if row_sum > 0 else 0
    
    
    
print(weight_edge)            

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [64]:
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [65]:
MAX_ITERATIONS = 50
d = 0.85
threshold = 0.0001

for it in range(MAX_ITERATIONS):
    prev_score = np.copy(scores)
    
    for i in range(vocab_len):
        summation = 0
        
        for j in range(vocab_len):
            summation += weight_edge[j][i] * prev_score[j]
        
        scores[i] = (1 - d) + d * summation
    

    if np.sum(np.fabs(prev_score - scores)) <= threshold:
        break
scores

array([ 0.7637757 ,  1.1885959 ,  0.7423884 ,  1.6908586 ,  0.54520833,
        0.587033  ,  1.1072263 ,  1.125002  ,  0.68257016,  0.85975224,
        0.6435138 ,  1.2635014 ,  0.71471065,  0.7669302 ,  1.2919149 ,
        0.6291068 ,  0.8125152 ,  0.70651966,  0.6856795 ,  1.0331086 ,
        0.75364166,  0.7276687 ,  0.66772217,  1.0666867 ,  0.6202339 ,
        0.6867033 ,  0.6978381 ,  0.8402579 ,  1.0535973 ,  1.3190597 ,
        0.6587766 ,  0.5487457 ,  0.6014266 ,  0.8065814 ,  1.8697902 ,
        1.1802754 ,  1.0471537 ,  0.75545406,  0.69359285,  0.7025833 ,
        2.8091419 ,  0.7455129 ,  0.60721886,  0.7472251 ,  0.71572506,
        3.8603883 ,  0.69436026,  1.5738283 ,  0.6185727 ,  0.7039955 ,
        1.1624595 ,  1.1101012 ,  1.2262847 ,  1.0894661 ,  0.79599667,
        0.66755676,  0.6548214 ,  0.70515704,  0.66268283,  1.9739664 ,
        1.0410352 ,  0.6782202 ,  0.62474614,  0.8300366 ,  0.6793581 ,
        0.852864  ,  1.0004439 ,  0.8236011 ,  0.70803094,  0.65

In [66]:
np.argsort(scores)

array([212,   4,  31, 115,   5,  95,  99,  93,  32, 246,  42, 114, 229,
        48,  24,  85,  62,  15, 204, 198, 127, 108, 138, 263, 157,  10,
       245, 181, 143, 207, 215, 258,  69, 179, 142, 172,  56,  30, 170,
       257,  96, 187, 249,  58, 190,  73,  83, 250, 244,  55,  22, 160,
       105, 163, 260, 148, 110, 131,  61, 141, 139,  64, 178, 164, 126,
        76,  79, 218,   8,  80, 106, 223, 242,  18, 238, 134,  25, 132,
       224, 254, 220, 201, 136,  89, 118, 186,  38, 185, 234, 243,  46,
       144, 165, 152, 196, 213,  26, 103, 177,  39, 233, 155, 214,  49,
       202,  57, 235,  17, 261,  90, 240,  68, 239, 169, 199, 128,  12,
       123,  44, 221,  84, 151, 116, 219, 180, 210, 120,  21, 168, 154,
       209, 113,  77, 112, 149, 241,   2, 147, 251,  41, 228, 256,  72,
        43, 259, 194, 101, 130, 227,  20, 107,  37, 184, 197, 100,   0,
       255,  13, 137, 146, 159, 230, 158, 192, 153, 264,  86, 232, 216,
       156, 166,  54,  33,  16, 247,  67,  63,  91, 176, 125, 17

In [67]:
sorted_index = np.flip(np.argsort(scores), 0)
sorted_index

array([ 81,  75,  45, 174,  97, 262, 195,  40, 252, 167, 206, 109, 237,
       182, 193, 208,  59,  34, 121,  70, 217, 200, 203,   3, 145, 162,
       122, 104, 129, 133,  47,  88, 205, 150,  94,  71, 225,  29,  98,
        14, 111, 231,  11, 236, 171,  52,  87,   1, 102,  35, 191, 189,
        82,  50, 211, 222, 226, 117, 161, 183, 124, 140,   7, 253, 119,
        51, 173,   6,  78,  53, 248,  23,  28,  36,  60,  19,  66,  92,
        74, 135,   9,  65,  27, 188, 175, 125, 176,  91,  63,  67, 247,
        16,  33,  54, 166, 156, 216, 232,  86, 264, 153, 192, 158, 230,
       159, 146, 137,  13, 255,   0, 100, 197, 184,  37, 107,  20, 227,
       130, 101, 194, 259,  43,  72, 256, 228,  41, 251, 147,   2, 241,
       149, 112,  77, 113, 209, 154, 168,  21, 120, 210, 180, 219, 116,
       151,  84, 221,  44, 123,  12, 128, 199, 169, 239,  68, 240,  90,
       261,  17, 235,  57, 202,  49, 214, 155, 233,  39, 177, 103,  26,
       213, 196, 152, 165, 144,  46, 243, 234, 185,  38, 186, 11

In [68]:
n = 3
for i in range(n):
    print("{} {}".format(id2vocab[sorted_index[i]], scores[sorted_index[i]]))

데이터 10.826644897460938
센터 4.422915458679199
활용 3.8603882789611816
