In [1]:
import re

import requests
from bs4 import BeautifulSoup
from konlpy.tag import Hannanum, Kkma, Komoran, Mecab, Okt
hannanum = Hannanum()
kkma = Kkma()
komoran = Komoran()
mecab = Mecab()
okt = Okt()

In [2]:
url = "https://news.naver.com/main/read.naver?mode=LSD&mid=sec&sid1=105&oid=018&aid=0004430108"
headers = {"user-agent":"Mozilla/5.0"}
response = requests.get(url, headers=headers)
html = BeautifulSoup(response.text, 'html.parser')

In [3]:
article = html.select_one("#articleBodyContents").text
article

'\n\n\n\n\n과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입, 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도.."개방성 강화"[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다. 새로운 산업 창출과 기존 산업의 변화에 이르는 ‘혁신성장’을 위한 센터가 문을 연다. 10개 분야에 걸쳐 ‘데이터 경제’의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다.22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한 ‘빅데이터 플랫폼 및 센터’ 출범식 행사를 개최했다. 유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다.◇10개 분야 100개 센터..3년간 1516억원 투입이미지: 픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다. 문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호(보안)에 대한 중요성을 강조하기도 했다.이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산·구축하고, 플랫폼은 이를 수집·분석·유통하는 역할을 담당한다. 과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며, 올해 우선 640억원 규모의 사업을 추진하고 있다.대상 분야는 △금융(BC카드) △환경(한국수자원공사) △문화(한국문화정보원) △교통(한국교통연구원) △헬스케어(국립암센터) △유통·소비(매일방송) △통신(KT) △중소기업(더존비즈온) △지역경제(경기도청) △산림(한국임업진흥원) 등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고, 다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원, 운영할 계획이다. 이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다.주요 활용 전략·사례를 보면

In [4]:
from nltk import sent_tokenize

sentences = sent_tokenize(article)
len(sentences)

12

In [5]:
sentence = sentences[0].strip()
sentence

'과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입, 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도.."개방성 강화"[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다.'

In [6]:
mecab.morphs(sentence)

['과기',
 '정통부',
 ',',
 '22',
 '일',
 '유영민',
 '장관',
 '등',
 '참석',
 '해',
 '기념행사',
 '2021',
 '년',
 '까지',
 '1516',
 '억',
 '원',
 '투입',
 ',',
 '5100',
 '여종',
 '데이터',
 '구축',
 '민간',
 '클라우드',
 '통한',
 '외부',
 '연계',
 '체계',
 '도',
 '.',
 '."',
 '개방',
 '성',
 '강화',
 '"[',
 '이',
 '데일리',
 '이재운',
 '기자',
 ']',
 '국가',
 '차원',
 '의',
 '빅',
 '데이터',
 '활용',
 '시대',
 '가',
 '열린다',
 '.']

In [7]:
mecab.pos(sentence)

[('과기', 'NNG'),
 ('정통부', 'NNG'),
 (',', 'SC'),
 ('22', 'SN'),
 ('일', 'NNBC'),
 ('유영민', 'NNP'),
 ('장관', 'NNG'),
 ('등', 'NNB'),
 ('참석', 'NNG'),
 ('해', 'XSV+EC'),
 ('기념행사', 'NNG'),
 ('2021', 'SN'),
 ('년', 'NNBC'),
 ('까지', 'JX'),
 ('1516', 'SN'),
 ('억', 'NR'),
 ('원', 'NNBC'),
 ('투입', 'NNG'),
 (',', 'SC'),
 ('5100', 'SN'),
 ('여종', 'NNG'),
 ('데이터', 'NNG'),
 ('구축', 'NNG'),
 ('민간', 'NNG'),
 ('클라우드', 'NNP'),
 ('통한', 'VV+ETM'),
 ('외부', 'NNG'),
 ('연계', 'NNG'),
 ('체계', 'NNG'),
 ('도', 'JX'),
 ('.', 'SF'),
 ('."', 'SY'),
 ('개방', 'NNG'),
 ('성', 'XSN'),
 ('강화', 'NNG'),
 ('"[', 'SY'),
 ('이', 'JKS'),
 ('데일리', 'NNP'),
 ('이재운', 'NNP'),
 ('기자', 'NNG'),
 (']', 'SSC'),
 ('국가', 'NNG'),
 ('차원', 'NNG'),
 ('의', 'JKG'),
 ('빅', 'NNG'),
 ('데이터', 'NNG'),
 ('활용', 'NNG'),
 ('시대', 'NNG'),
 ('가', 'JKS'),
 ('열린다', 'VV+EF'),
 ('.', 'SF')]

In [8]:
import nltk
from nltk import bigrams, word_tokenize
from nltk.util import ngrams


In [9]:
bigram_list = bigrams(mecab.morphs(sentence))
bigram_list

<generator object bigrams at 0x0000019A516898C8>

In [10]:
for token in bigram_list:
    print(token)

('과기', '정통부')
('정통부', ',')
(',', '22')
('22', '일')
('일', '유영민')
('유영민', '장관')
('장관', '등')
('등', '참석')
('참석', '해')
('해', '기념행사')
('기념행사', '2021')
('2021', '년')
('년', '까지')
('까지', '1516')
('1516', '억')
('억', '원')
('원', '투입')
('투입', ',')
(',', '5100')
('5100', '여종')
('여종', '데이터')
('데이터', '구축')
('구축', '민간')
('민간', '클라우드')
('클라우드', '통한')
('통한', '외부')
('외부', '연계')
('연계', '체계')
('체계', '도')
('도', '.')
('.', '."')
('."', '개방')
('개방', '성')
('성', '강화')
('강화', '"[')
('"[', '이')
('이', '데일리')
('데일리', '이재운')
('이재운', '기자')
('기자', ']')
(']', '국가')
('국가', '차원')
('차원', '의')
('의', '빅')
('빅', '데이터')
('데이터', '활용')
('활용', '시대')
('시대', '가')
('가', '열린다')
('열린다', '.')


In [11]:
trigram_list = ngrams(mecab.morphs(sentence), 3)
trigram_list

In [12]:
for token in trigram_list:
    print(token)

('과기', '정통부', ',')
('정통부', ',', '22')
(',', '22', '일')
('22', '일', '유영민')
('일', '유영민', '장관')
('유영민', '장관', '등')
('장관', '등', '참석')
('등', '참석', '해')
('참석', '해', '기념행사')
('해', '기념행사', '2021')
('기념행사', '2021', '년')
('2021', '년', '까지')
('년', '까지', '1516')
('까지', '1516', '억')
('1516', '억', '원')
('억', '원', '투입')
('원', '투입', ',')
('투입', ',', '5100')
(',', '5100', '여종')
('5100', '여종', '데이터')
('여종', '데이터', '구축')
('데이터', '구축', '민간')
('구축', '민간', '클라우드')
('민간', '클라우드', '통한')
('클라우드', '통한', '외부')
('통한', '외부', '연계')
('외부', '연계', '체계')
('연계', '체계', '도')
('체계', '도', '.')
('도', '.', '."')
('.', '."', '개방')
('."', '개방', '성')
('개방', '성', '강화')
('성', '강화', '"[')
('강화', '"[', '이')
('"[', '이', '데일리')
('이', '데일리', '이재운')
('데일리', '이재운', '기자')
('이재운', '기자', ']')
('기자', ']', '국가')
(']', '국가', '차원')
('국가', '차원', '의')
('차원', '의', '빅')
('의', '빅', '데이터')
('빅', '데이터', '활용')
('데이터', '활용', '시대')
('활용', '시대', '가')
('시대', '가', '열린다')
('가', '열린다', '.')


In [13]:
okt = Okt()

example = "'과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입, 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도..개방성 강화[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다."
stop_words = "기념행사2021년까지 1516억원 투입 국가 차원의 빅데이터 활용 시대가 열린다"

stop_words = set(stop_words.split(' '))
word_tokens = okt.morphs(example)

result = [word for word in word_tokens if not word in stop_words]

print('불용어 제거 전 :',word_tokens) 
print('불용어 제거 후 :',result)

불용어 제거 전 : ["'", '과', '기', '정통부', ',', '22일', '유영민', '장관', '등', '참석', '해', '기념', '행사', '2021년', '까지', '1516억원', '투입', ',', '5100', '여종', '데이터', '구축', '민간', '클라우드', '통한', '외부', '연', '계', '체계', '도', '..', '개방', '성', '강화', '[', '이데일리', '이', '재운', '기자', ']', '국가', '차원', '의', '빅데이터', '활용', '시대', '가', '열', '린다', '.']
불용어 제거 후 : ["'", '과', '기', '정통부', ',', '22일', '유영민', '장관', '등', '참석', '해', '기념', '행사', '2021년', '까지', ',', '5100', '여종', '데이터', '구축', '민간', '클라우드', '통한', '외부', '연', '계', '체계', '도', '..', '개방', '성', '강화', '[', '이데일리', '이', '재운', '기자', ']', '차원', '의', '시대', '가', '열', '린다', '.']


In [14]:
docs = ['과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입' 
        '5100여종 데이터 구축민간 클라우드 통한 외부연계체계도'      
        '개방성 강화[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다.']

In [15]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['과기정통부,',
  '22일',
  '유영민',
  '장관',
  '등',
  '참석해',
  '기념행사2021년까지',
  '1516억원',
  '투입5100여종',
  '데이터',
  '구축민간',
  '클라우드',
  '통한',
  '외부연계체계도개방성',
  '강화[이데일리',
  '이재운',
  '기자]',
  '국가',
  '차원의',
  '빅데이터',
  '활용',
  '시대가',
  '열린다.']]

In [16]:
word2id = {}

index = 0
for doc in doc_ls:
    for token in doc:
        if token not in word2id:
            word2id[token] = index
            index += 1

word2id

{'과기정통부,': 0,
 '22일': 1,
 '유영민': 2,
 '장관': 3,
 '등': 4,
 '참석해': 5,
 '기념행사2021년까지': 6,
 '1516억원': 7,
 '투입5100여종': 8,
 '데이터': 9,
 '구축민간': 10,
 '클라우드': 11,
 '통한': 12,
 '외부연계체계도개방성': 13,
 '강화[이데일리': 14,
 '이재운': 15,
 '기자]': 16,
 '국가': 17,
 '차원의': 18,
 '빅데이터': 19,
 '활용': 20,
 '시대가': 21,
 '열린다.': 22}

In [17]:
word2id = {}


for doc in doc_ls:
    for token in doc:
        if token not in word2id:
            word2id[token] = len(word2id)


word2id

{'과기정통부,': 0,
 '22일': 1,
 '유영민': 2,
 '장관': 3,
 '등': 4,
 '참석해': 5,
 '기념행사2021년까지': 6,
 '1516억원': 7,
 '투입5100여종': 8,
 '데이터': 9,
 '구축민간': 10,
 '클라우드': 11,
 '통한': 12,
 '외부연계체계도개방성': 13,
 '강화[이데일리': 14,
 '이재운': 15,
 '기자]': 16,
 '국가': 17,
 '차원의': 18,
 '빅데이터': 19,
 '활용': 20,
 '시대가': 21,
 '열린다.': 22}

In [18]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
print(word2id)
[word2id[token] for doc in doc_ls for token in doc]
print(word2id)

defaultdict(<function <lambda> at 0x0000019A517FCEE8>, {})
defaultdict(<function <lambda> at 0x0000019A517FCEE8>, {'과기정통부,': 0, '22일': 1, '유영민': 2, '장관': 3, '등': 4, '참석해': 5, '기념행사2021년까지': 6, '1516억원': 7, '투입5100여종': 8, '데이터': 9, '구축민간': 10, '클라우드': 11, '통한': 12, '외부연계체계도개방성': 13, '강화[이데일리': 14, '이재운': 15, '기자]': 16, '국가': 17, '차원의': 18, '빅데이터': 19, '활용': 20, '시대가': 21, '열린다.': 22})


In [19]:
word2id={}
for doc in doc_ls:
    for token in doc:
        if token not in word2id:
            word2id[token]=len(word2id)
word2id

{'과기정통부,': 0,
 '22일': 1,
 '유영민': 2,
 '장관': 3,
 '등': 4,
 '참석해': 5,
 '기념행사2021년까지': 6,
 '1516억원': 7,
 '투입5100여종': 8,
 '데이터': 9,
 '구축민간': 10,
 '클라우드': 11,
 '통한': 12,
 '외부연계체계도개방성': 13,
 '강화[이데일리': 14,
 '이재운': 15,
 '기자]': 16,
 '국가': 17,
 '차원의': 18,
 '빅데이터': 19,
 '활용': 20,
 '시대가': 21,
 '열린다.': 22}

In [25]:
import numpy as np
import pandas as pd

BoW_ls = []

for doc in doc_ls:
    bow = np.zeros(len(word2id), dtype=int)
    for token in doc:
        bow[word2id[token]] += 1
    BoW_ls.append(bow.tolist())
    
print(BoW_ls)

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]


In [26]:
from IPython.core import display as ICD

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
for i in range(len(docs)):
    print("문서 {} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
    print("\n")

문서 0 : 과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입5100여종 데이터 구축민간 클라우드 통한 외부연계체계도개방성 강화[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다.


과기정통부,  22일  유영민  장관  등  참석해  기념행사2021년까지  1516억원  투입5100여종  데이터  ...  \
0       1    1    1   1  1    1            1       1         1    1  ...   

   외부연계체계도개방성  강화[이데일리  이재운  기자]  국가  차원의  빅데이터  활용  시대가  열린다.  
0           1        1    1    1   1    1     1   1    1     1  

[1 rows x 23 columns]

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
BoW.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]], dtype=int64)

In [28]:
from IPython.core import display as ICD

vocab = count_vect.get_feature_names_out()
vocab

array(['1516억원', '22일', '강화', '과기정통부', '구축민간', '국가', '기념행사2021년까지', '기자',
       '데이터', '빅데이터', '시대가', '열린다', '외부연계체계도개방성', '유영민', '이데일리', '이재운',
       '장관', '차원의', '참석해', '클라우드', '통한', '투입5100여종', '활용'], dtype=object)

In [29]:
for i in range(len(docs)):
    print("문서 {} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
    print("\n")

문서 0 : 과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입5100여종 데이터 구축민간 클라우드 통한 외부연계체계도개방성 강화[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다.


1516억원  22일  강화  과기정통부  구축민간  국가  기념행사2021년까지  기자  데이터  빅데이터  ...  유영민  \
0       1    1   1      1     1   1            1   1    1     1  ...    1   

   이데일리  이재운  장관  차원의  참석해  클라우드  통한  투입5100여종  활용  
0     1    1   1    1    1     1   1         1   1  

[1 rows x 23 columns]

In [30]:
TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)
TDM

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [31]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token], i] += 1
TDM

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [32]:
doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
df_TDM = pd.DataFrame(TDM, columns=doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어', inplace=True)
df_TDM

문서0
단어              
과기정통부,         1
22일            1
유영민            1
장관             1
등              1
참석해            1
기념행사2021년까지    1
1516억원         1
투입5100여종       1
데이터            1
구축민간           1
클라우드           1
통한             1
외부연계체계도개방성     1
강화[이데일리        1
이재운            1
기자]            1
국가             1
차원의            1
빅데이터           1
활용             1
시대가            1
열린다.           1

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]], dtype=int64)

In [34]:
from gensim.matutils import sparse2full

vocab = [id2word[key] for key in id2word.keys()]
DTM_matrix = [sparse2full(doc, len(vocab)).tolist() for doc in tfidf]
pd.DataFrame(DTM_matrix, columns=vocab)

NameError: name 'id2word' is not defined