In [53]:
tokens = ["딸기", "바나나", "사과", "딸기", "파인애플"]
# nodes =  list(set(tokens))
vocab = ["바나나", "사과", "파인애플", "딸기"]

vocab2id = { vocab[i] : i for i in range(len(vocab))}
id2vocab = { i : vocab[i] for i in range(len(vocab))}

print(vocab2id)
print(id2vocab)

{'바나나': 0, '사과': 1, '파인애플': 2, '딸기': 3}
{0: '바나나', 1: '사과', 2: '파인애플', 3: '딸기'}


In [57]:
import numpy as np

vocab_len = len(vocab)
weight_edge = np.zeros((vocab_len, vocab_len), dtype=np.float32)
scores = np.ones(vocab_len, dtype=np.float32)

window_size = 2

covered_coocurrences = []

for window_start in range(0, len(tokens)-window_size + 1):
    window = tokens[window_start : window_start + window_size]
    for i in range(window_size - 1):
        for j in range(i+1, window_size):
            
            if window[i] in vocab and window[j] in vocab:
                index_of_i = window_start + i
                index_of_j = window_start + j

                if (index_of_i, index_of_j) not in covered_coocurrences:
                    weight_edge[vocab2id[window[i]]][vocab2id[window[j]]] = 1
                    weight_edge[vocab2id[window[j]]][vocab2id[window[i]]] = 1
                    covered_coocurrences.append((index_of_i, index_of_j))

print(weight_edge)

for i in range(vocab_len):
    row_sum =  weight_edge[i].sum()
    weight_edge[i] = weight_edge[i] / row_sum if row_sum > 0 else 0
    
                
                
weight_edge          

[[0. 1. 0. 1.]
 [1. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 1. 1. 0.]]


array([[0.        , 0.5       , 0.        , 0.5       ],
       [0.5       , 0.        , 0.        , 0.5       ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.33333334, 0.33333334, 0.33333334, 0.        ]], dtype=float32)

In [59]:
scores

array([1., 1., 1., 1.], dtype=float32)

In [81]:
MAX_ITERATIONS = 50
d = 0.85
threshold = 0.0001

for it in range(MAX_ITERATIONS):
    prev_score = np.copy(scores)
    
    for i in range(vocab_len):
        
        summation = 0
        
        for j in range(vocab_len):
            summation += weight_edge[j][i] *  prev_score[j]
            
        scores[i] = (1 - d) + d * summation
            
    if np.sum(np.fabs(prev_score - scores)) < threshold:
        break
        
scores

array([0.9837155 , 0.9837155 , 0.56564105, 1.4669281 ], dtype=float32)

In [82]:
np.argsort(scores)

array([2, 0, 1, 3], dtype=int64)

In [84]:
sorted_index = np.flip(np.argsort(scores), 0)
sorted_index

array([3, 1, 0, 2], dtype=int64)

In [87]:
n = 3
for i in range(n):
    print("{} {}".format(id2vocab[sorted_index[i]], scores[sorted_index[i]]))

딸기 1.4669281244277954
사과 0.9837154746055603
바나나 0.9837154746055603
