In [3]:
import numpy as np

In [4]:
x = np.arange(1, 4)
y = np.arange(4, 7)
z = np.arange(8, 11)
print(x)
print(y)
print(z)

[1 2 3]
[4 5 6]
[ 8  9 10]


In [10]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [11]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)

In [12]:
print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
print(x.shape)
print(y.shape)

(2, 5)
(2, 5)


In [15]:
z = np.concatenate([x, y])
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
z.shape

(4, 5)

In [17]:
z = np.concatenate([x, y], axis=1)
print(z.shape)
z

(2, 10)


array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [18]:
x = np.arange(12)

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
np.split(x, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [22]:
np.split(x, 5)

ValueError: array split does not result in an equal division

In [23]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.split(x, 2)

ValueError: array split does not result in an equal division

In [25]:
np.split(x, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [26]:
x = np.arange(12).reshape(4, -1)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
np.split(x, 2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]