In [37]:
import numpy as np

In [38]:
x = np.arange(6).reshape(3, 2)
y = np.arange(6).reshape(2, 3)
print(x)
print("------------")
print(y)

[[0 1]
 [2 3]
 [4 5]]
------------
[[0 1 2]
 [3 4 5]]


In [13]:
z = x.dot(y)
z

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [14]:
np.transpose(x)

array([[0, 2, 4],
       [1, 3, 5]])

In [15]:
np.mean(x)

2.5

In [16]:
np.median(x)

2.5

In [18]:
np.median(z)

14.0

In [20]:
np.std(x)

1.707825127659933

In [21]:
np.std(z)

9.510228411791404

In [22]:
np.var(x)

2.9166666666666665

In [23]:
np.var(z)

90.44444444444444

In [32]:
np.sum(x)

15

In [33]:
np.sum(x, axis=0)

array([6, 9])

In [35]:
np.sum(x, axis=1)

array([1, 5, 9])

In [41]:
x = np.arange(3, 4)
x

array([3])

In [43]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
print(x)
print(y)

[[10]
 [20]
 [30]]
[1 2 3]


In [48]:
z = np.random.randint(1, 101, size=(2, 10, 10))
z

array([[[ 68,  62,  28,  90,  91,  17,  23,  66,  42,  33],
        [  3,  27,   9,   6,  37,  90,  82,  32,  83,  22],
        [ 41,  97,  21,  29,  87,  27,  53,  72,  80,  98],
        [  6,  70,  73,  26,   7,  74,  60,  88,  25,  62],
        [ 83,  96,  70,  75,  85,  73,  88,  96,  89,  73],
        [ 11,  66,   3,  81,  24,  75,  15,  28,  62,  59],
        [ 48,  31,  28,  77,  49,  29,   6,  61,  34,  91],
        [ 74,  71,   7,   1, 100,  16,  33,  15,   5,  12],
        [ 92,   3,  77,  62,  48,  58,   5,  82,  44,  75],
        [ 64,  56,  42,  40,  22,  47,  14,   6,  68,  30]],

       [[ 66,   6,  36,  81,  28,  91,  18,  19,  64,  61],
        [  6,  57,  83,  19,   5,  80,  43,  29,  54,  91],
        [ 42,  98,  69,  20,  32,  94,  71,   2,  42,  91],
        [ 74,  47,  34,  60,  77,  18,  62,  87,  95,  88],
        [ 42,  93,  73,  89,  20,  10,  61,  11,  12,  30],
        [ 59,  94,  26, 100,  65,  77,  22,  34,   1,  19],
        [ 68,  45,  23,  86,  63,  98,

In [49]:
z[1. 5:, 5:]

SyntaxError: invalid syntax (Temp/ipykernel_19160/2528080678.py, line 1)