In [19]:
import numpy as np

In [6]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

In [21]:
%%time
sum_matrix = []
for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append( matrix_1[i][j] + matrix_2[i][j])
        
    sum_matrix.append(temp)
    
print(sum_matrix)

[[6, 8], [10, 12]]
Wall time: 0 ns


In [25]:
np_sum_matrix = np.array(matrix_1) + np.array(matrix_2)
print(np_sum_matrix)
np_sum_matrix

[[ 6  8]
 [10 12]]


array([[ 6,  8],
       [10, 12]])

In [24]:
%%time
sum_matrix = []
for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append( matrix_1[i][j] + matrix_2[i][j] + 1)
        
    sum_matrix.append(temp)
    
print(sum_matrix)

[[7, 9], [11, 13]]
Wall time: 0 ns


In [26]:
np_add_one_matrix = np.array(matrix_1) + 1
print(np_add_one_matrix)
np_add_one_matrix

[[2 3]
 [4 5]]


array([[2, 3],
       [4, 5]])

In [28]:
import time
time.time()

1639964027.992948

In [29]:
import time
size = 10000000
#list
x = list(range(size))
y = list(range(size))
start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린시간", time.time()-start_time)
#adlist
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("넘파이 걸린시간", time.time()-start_time)


리스트 걸린시간 1.485994577407837
넘파이 걸린시간 0.1557598114013672


In [30]:
for i in range(size):
    (x[i] + x[i])


In [31]:
a = np.array(list(range(10)))

In [33]:
a.dtype

dtype('int32')

In [43]:
a = np.array(list(range(10)), dtype=np.float32)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [45]:
type(a)

numpy.ndarray

In [48]:
b = np.array(a)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [53]:
x = np.uint(32)

In [54]:
x.dtype

dtype('uint32')

In [55]:
x = np.array([1, 2, 3, 4])
print(x.dtype)

int32


In [56]:
x = np.float32([1, 2, 3, 4])
x.dtype

dtype('float32')

In [58]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x.dtype)

float32
