In [1]:
docs = ["나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해", 
        "나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 좋아해"]

In [15]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '좋아해']]

In [16]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [18]:
import numpy as np
BoW_ls = []

for doc in doc_ls:
    bow = np.zeros(len(word2id), dtype=int)
    for token in doc:
        bow[word2id[token]] += 1
    BoW_ls.append(bow.tolist())
    
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 0], [1, 1, 2, 2, 1, 1, 0, 0]]

In [5]:
word2id = {}

index = 0
for doc in docs:
    for token in doc:
        if token not in word2id:
            word2id[token] = index
            index += 1

            
word2id

{'나': 0,
 '는': 1,
 ' ': 2,
 '양': 3,
 '념': 4,
 '치': 5,
 '킨': 6,
 '을': 7,
 '좋': 8,
 '아': 9,
 '해': 10,
 '하': 11,
 '지': 12,
 '만': 13,
 '후': 14,
 '라': 15,
 '이': 16,
 '드': 17,
 '싫': 18,
 '어': 19}

In [6]:
import numpy as np
BoW_ls = []

for doc in docs:
    bow = np.zeros(len(word2id), dtype=int)
    for token in doc:
        bow[word2id[token]] += 1
    BoW_ls.append(bow.tolist())
    
BoW_ls

[[1, 1, 7, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 7, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0]]

In [8]:
from IPython.core import display as ICD
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
for i in range(len(docs)):
    print("anstj {} : {}".format(i, doc[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
    print("\n")

anstj 0 : 나


나  는     양  념  치  킨  을  좋  아  해  하  지  만  후  라  이  드  싫  어
0  1  1  7  1  1  2  2  2  1  1  2  1  1  1  1  1  1  1  1  1



anstj 1 : 는


나  는     양  념  치  킨  을  좋  아  해  하  지  만  후  라  이  드  싫  어
0  1  1  7  1  1  2  2  2  2  2  2  1  1  1  1  1  1  1  0  0

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
BoW.toarray()

array([[1, 1, 1, 1, 2, 1, 1],
       [1, 0, 1, 2, 2, 1, 1]], dtype=int64)

In [11]:
from IPython.core import display as ICD

vocab = count_vect.get_feature_names_out()
vocab

array(['나는', '싫어해', '양념', '좋아해', '치킨을', '하지만', '후라이드'], dtype=object)

In [13]:
docs[0]

'나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해'

In [12]:
for i in range(len(docs)):
    print("문서 {} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
    print("\n")

문서 0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  싫어해  양념  좋아해  치킨을  하지만  후라이드
0   1    1   1    1    2    1     1



문서 1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 좋아해


나는  싫어해  양념  좋아해  치킨을  하지만  후라이드
0   1    0   1    2    2    1     1

In [23]:
!pip install gensim

In [29]:
import gensim
from gensim import corpora

docs = ["나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해", 
        "나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 좋아해"]

doc_ls = [doc.split() for doc in docs]
doc_ls

id2word = corpora.Dictionary(doc_ls)
BoW = [id2word.doc2bow(doc) for doc in doc_ls]
BoW

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 2), (5, 1), (6, 1)],
 [(0, 1), (2, 1), (3, 2), (4, 2), (5, 1), (6, 1)]]

In [34]:
for key in id2word.keys(): 
    print("{} : {}".format(key, id2word[key]))

0 : 나는
1 : 싫어해
2 : 양념
3 : 좋아해
4 : 치킨을
5 : 하지만
6 : 후라이드


In [37]:
from gensim.matutils import sparse2full

sparse2full(BoW[0], len(vocab))

array([1., 1., 1., 1., 2., 1., 1.], dtype=float32)

In [39]:
from gensim.matutils import sparse2full #순서, 형태 변환(sparse2ful)

vocab = [id2word[key] for key in id2word.keys()]
for i in range(len(docs)):
    print("문서 {} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[0], len(vocab))], columns=vocab))
    print("\n")

문서 0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  싫어해   양념  좋아해  치킨을  하지만  후라이드
0  1.0  1.0  1.0  1.0  2.0  1.0   1.0



문서 1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 좋아해


나는  싫어해   양념  좋아해  치킨을  하지만  후라이드
0  1.0  1.0  1.0  1.0  2.0  1.0   1.0

In [48]:
TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int) 
TDM

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [49]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token], i] +=1
TDM

array([[1, 1],
       [1, 1],
       [2, 2],
       [1, 2],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0]])

In [51]:
doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
df_TDM = pd.DataFrame(TDM, columns=doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어', inplace=True)
df_TDM

문서0  문서1
단어            
나는      1    1
양념      1    1
치킨을     2    2
좋아해     1    2
하지만     1    1
후라이드    1    1
싫어해     1    0
나       0    0

In [65]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 1, 1, 1, 2, 1, 1],
       [1, 0, 1, 2, 2, 1, 1]], dtype=int64)

In [67]:
doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
vocab = count_vect.get_feature_names_out()
df_TDM = pd.DataFrame(DTM.toarray().T, columns=doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어', inplace=True)
df_TDM

문서0  문서1
단어            
나는      1    1
싫어해     1    0
양념      1    1
좋아해     1    2
치킨을     2    2
하지만     1    1
후라이드    1    1

In [62]:
doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
df_DTM = pd.DataFrame(DTM)
df_DTM['단어'] = vocab
df_DTM.set_index('단어', inplace=True)
df_DTM

0  1
단어        
나는    1  1
양념    1  1
치킨을   2  2
좋아해   1  2
하지만   1  1
후라이드  1  1
싫어해   1  0
나     0  0

In [98]:
import pandas as pd # 데이터프레임 사용을 위해
from math import log # IDF 계산을 위해

docs = ["오늘 동물원에서 원숭이를 봤어", 
       "오늘 동물원에서 코끼리를 봤어 봤어",
       "동물원에서 원숭이에게 바나나를 줬어 바나나를"]

vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()

In [85]:
DTM = [doc.split() for doc in docs]
DTM

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [86]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 2, 1, 0, 0, 0, 1],
       [1, 2, 0, 0, 0, 1, 1, 0]], dtype=int64)

In [87]:
doc_names = ['문서'+str(i) for i in range(len(docs))]
vocab = count_vect.get_feature_names_out()
df_TDM = pd.DataFrame(DTM.toarray().T, columns=doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어', inplace=True)
df_TDM

문서0  문서1  문서2
단어                  
동물원에서    1    1    1
바나나를     0    0    2
봤어       1    2    0
오늘       1    1    0
원숭이를     1    0    0
원숭이에게    0    0    1
줬어       0    0    1
코끼리를     0    1    0

In [88]:
df_TDM.T

단어   동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
문서0      1     0   1   1     1      0   0     0
문서1      1     0   2   1     0      0   0     1
문서2      1     2   0   0     0      1   1     0

In [97]:
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()

In [101]:
# 총 문서의 수
N = len(docs) 

def tf(t, d):
      return d.count(t)

def idf(t):
    df = 0
    for doc in docs:
        df += t in doc
        return log(N/(df+1))

def tfidf(t, d):
      return tf(t,d)* idf(t)

In [104]:
result = []

# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_

동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   1   1     1      0   0     0
1      1     0   2   1     0      0   0     1
2      1     2   0   0     0      1   1     0

In [109]:
import pandas as pd # 데이터프레임 사용을 위해
from math import log # IDF 계산을 위해

docs = [
  "오늘 동물원에서 원숭이를 봤어", 
       "오늘 동물원에서 코끼리를 봤어 봤어",
       "동물원에서 원숭이에게 바나나를 줬어 바나나를"
] 
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()

In [110]:
# 총 문서의 수
N = len(docs) 

def tf(t, d):
    return d.count(t)

def idf(t):
    df = 0
    for doc in docs:
        df += t in doc
        return log(N/(df+1))

def tfidf(t, d):
    return tf(t,d)* idf(t)

In [111]:
result = []

# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_

동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   1   1     1      0   0     0
1      1     0   2   1     0      0   0     1
2      1     2   0   0     0      1   1     0

In [113]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])
idf_

IDF
동물원에서  0.405465
바나나를   1.098612
봤어     0.405465
오늘     0.405465
원숭이를   0.405465
원숭이에게  1.098612
줬어     1.098612
코끼리를   1.098612

In [115]:
result = []
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_

동물원에서      바나나를        봤어        오늘      원숭이를     원숭이에게        줬어  \
0  0.405465  0.000000  0.405465  0.405465  0.405465  0.000000  0.000000   
1  0.405465  0.000000  0.810930  0.405465  0.000000  0.000000  0.000000   
2  0.405465  2.197225  0.000000  0.000000  0.000000  1.098612  1.098612   

       코끼리를  
0  0.000000  
1  1.098612  
2  0.000000

In [116]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [126]:
DTM = np.zeros((len(doc_ls), len(word2id)), dtype=int)
DTM

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [127]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        DTM[i, word2id[token]] +=1
DTM

array([[1, 1, 2, 1, 1, 1, 1],
       [1, 1, 2, 2, 1, 1, 0]])

In [132]:
TF = DTM = np.zeros((len(doc_ls), len(word2id)))

doc_len = len(doc_ls)
word_len = len(word2id)

for i, doc in enumerate(doc_ls):
    sum_doc = DTM[i].sum()
    for j in range(word_len):
        TF[i, j] = DTM[i, j] / float(sum_doc)
        
TF

C:\Users\user\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


array([[nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan]])

In [136]:
import math

IDF = np.zeros(len(word_len))
for i in range(word_len):
    idf[i] = -math.log10(np.nonzero([DTM[:, i]]) / doc_len)
    
IDF

TypeError: object of type 'int' has no len()

In [137]:
TFIDF = np.zeros(TF.shape)
TFIDF

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [140]:
for i in range(doc_len):
    for j in range(word_len):
        TFIDF[i, j] = TF[i, j] * IDF[j]
        
TFIDF

NameError: name 'IDF' is not defined