In [9]:
import numpy as np

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
x = np.arange(24).reshape(2, 3, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
x = np.arange(16).reshape(2, 2, 2, 2)
x

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [23]:
x = np.arange([[1, 2], [3, 4], [5, 6]])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [24]:
class Person:
    def __init__(self):
        self.gender = "Not reveal"
        self.name = ""
        
    def get_gender(self):
        return self_gender
    
    def get_name(self):
        return self.name
    

In [34]:
class Male(Person):
    def __init__(self):
        super()._init__()
        
    def get_gender(self):
        return self.gender
        self.gender = "Male"

class Female(Person):
    def __init__(self):
        super()._init__()
        self.gender = "Female"
        
    def get_gender(self):
        return self.gender


In [36]:
np.random.rand(5,5)

array([[0.09017243, 0.0142608 , 0.21882232, 0.33602714, 0.4914074 ],
       [0.51425003, 0.29386569, 0.86940877, 0.1798887 , 0.08505734],
       [0.41780389, 0.73541653, 0.31757678, 0.03652124, 0.8218764 ],
       [0.4071758 , 0.92378134, 0.79455615, 0.56617157, 0.45196029],
       [0.92509239, 0.82878481, 0.721212  , 0.9131505 , 0.35733255]])

In [40]:
np.random.randint(1, 10)

3

In [45]:
np.random.randint(1, 10, size=(5, 5))

array([[7, 2, 8, 5, 7],
       [9, 3, 1, 4, 8],
       [4, 9, 6, 1, 4],
       [7, 4, 8, 5, 3],
       [4, 4, 9, 4, 6]])

In [47]:
x = np.array([3, 6, 9, 12])
np.random.choice(x, size=(3, 4))

array([[ 6,  6,  3,  9],
       [ 6,  3, 12,  3],
       [ 9,  6,  9,  3]])

In [48]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [1]:
np.eye(4)

NameError: name 'np' is not defined

In [2]:
x = np.arange(1, 4)
y = np.arange(4, 7)
z = np.arange(8, 11)
print(x)
print(y)
print(z)

NameError: name 'np' is not defined